[FEATURE#35371] Provider de traduction Abort Api
etna-alternance/composer-translation-provider pull request #1
Opened 2016-10-31 15:41 UTC by rinaz-a

On crée ce petit provider afin de traduire les messages abort de l'api dans le language de l'utilisateur, le reste est dans le readMe :)

2016-11-02 08:32 UTC, TinyTinyKame requested changes
J'ai une autre question du coup, est-ce que les headers que tu rajoutes disparaissent lorsque le réponse est envoyée?

2016-11-02 08:32 UTC, TinyTinyKame commented on README.md
> +Ce provider nous permettre de revoyer les messages `abort` dans la langue de l'utilisateur à partir de nos API vers nos clients.
`+Ce provider va nous permettre de renvoyer les messages `abort` dans la langue de l'utilisateur à partir de nos API vers nos clients.`

2016-11-02 08:32 UTC, TinyTinyKame commented on README.md
> +Il faut ajouter un (ou plusieurs) fichier de traduction et les ajouter au EtnaConfig.php à la façon suivante :
`de la façon`

2016-11-02 08:32 UTC, TinyTinyKame commented on README.md
> +        'Super-Translation' => json_encode(['%entity%' => $entity_name])
`Super-Translation`? genre, t'as pas trouvé un autre nom de header :p

2016-11-02 08:32 UTC, TinyTinyKame commented on src/TranslationProvider.php
> +                $tokens = json_decode($response->headers->get('Super-Translation', "[]"), true);
un autre nom que `Super-Translation` quand même

2016-11-02 08:38 UTC, Leosten commented on README.md
> +`%name%` étant ici un token (optionel) que l'on peut ajouter à la traduction, il faudra le placer dans le header du `abort` comme ceci :
`(optionnel)`

2016-11-02 08:38 UTC, gdubost commented on composer.json
> +        "dflydev/doctrine-orm-service-provider": "2.x"
pourquoi ?

2016-11-02 08:39 UTC, gdubost commented on src/TranslationProvider.php
> +                $content = json_decode($response->getContent(), TRUE);
les minuscules c'est bien aussi

2016-11-02 08:40 UTC, gdubost commented
Mais du coup il manque deux trois trucs, faudrait gérer la langue principale du navigateur et rajouter des tests ^^

2016-11-02 08:46 UTC, lapwil requested changes

2016-11-02 08:46 UTC, lapwil commented on README.md
> +/!\ Le nom du token ne doit pas contenir de caractères spéciaux, on préfèrera ici le camelCase.
dommage que ton exemple ne reprennes pas cette idée de camelCase 🐫  tu pourrais choisir `%entityName%` plutôt

2016-11-02 08:46 UTC, lapwil commented on src/TranslationProvider.php
> +use Silex\Provider\DoctrineServiceProvider;
no need for this

2016-11-02 08:53 UTC, rinaz-a commented on composer.json
> +        "dflydev/doctrine-orm-service-provider": "2.x"
whaaat je l'ai enlevé chez moi, chelou

2016-11-02 08:54 UTC, rinaz-a commented
les tests sont sur l'API @gdubost

2016-11-02 10:54 UTC, lapwil requested changes

2016-11-02 10:54 UTC, lapwil commented on src/TranslationProvider.php
> +                    $tokens = json_decode($response->headers->get('Super-Translation', "[]"), true);
comme disait @TinyTinyKame tu veux pas faire quelque chose d'autre que `Super-Translation` genre `Api-Translation` ou un truc plus explicite 😛

2016-11-02 13:04 UTC, rinaz-a commented on src/TranslationProvider.php
> +                    $tokens = json_decode($response->headers->get('Super-Translation', "[]"), true);
étrangement je pensais l'avoir edit mais j'ai dut edit celui que j'ai pour mes tests dans contract-api, my bad

2016-11-03 09:54 UTC, lapwil approved these changes
OK quand yaura les tests

2016-11-18 10:55 UTC, staciekith commented on src/TranslationProvider.php
> +                $response->headers->remove('Translation');
Ca bug pas si on n'a pas le header Translation ?

2016-11-18 11:04 UTC, staciekith commented on Tests/Bootstrap/FeatureContext.php
> +    public function jeDevraisAvoirUnResultatDApiEnJSON()
Ces fonctions sont déjà dans le composer-behat-utils non ?

2016-11-18 11:05 UTC, staciekith commented on composer.json
> +        "etna/composer-behat-utils": "2.x-dev",
C'est required mais pas utilisé :p idem pour doctrine juste en dessous

2016-11-18 13:24 UTC, rinaz-a commented on composer.json
> +        "etna/composer-behat-utils": "2.x-dev",
Si c'est utilisé va voir dans le behat.yml j'utilise MainContext

2016-11-18 13:26 UTC, rinaz-a commented on Tests/Bootstrap/FeatureContext.php
> +    public function jeDevraisAvoirUnResultatDApiEnJSON()
Oui mais elles nécéssitent une base de test dont je n'ai pas besoin si on appelle ApiContext && DoctrineContext du coup je les ai un peu mod pour moins ajouter de trucs useless

2016-11-18 13:26 UTC, Leosten commented on app/Utils/Silex/Translator/abort.fr.xlf
> +                <target>Résponsable non trouvé : %id%</target>
`Responsable`

2016-11-18 13:26 UTC, rinaz-a commented on composer.json
> +        "etna/composer-behat-utils": "2.x-dev",
Mais vrai pour doctrine je croyais l'avoir retiré mais y'en avait 3...

2016-11-18 13:28 UTC, rinaz-a commented on src/TranslationProvider.php
> +                $response->headers->remove('Translation');
Non ça ne bug pas mais je vais le mettre dans le isset cat ça ne sert à rien de faire appel à cette fonction quand on en a pas besoin ;)

2016-11-21 10:59 UTC, lapwil requested changes

2016-11-21 10:59 UTC, lapwil commented on Tests/Bootstrap/FeatureContext.php
> +        if ($body !== null) {
ta condition est dans le mauvais sens!

exemple: `$variable === 'toto'` => `'toto' === $variable`

2016-11-21 10:59 UTC, lapwil commented on Tests/Bootstrap/FeatureContext.php
> +        if ($body !== null) {
ta condition est dans le mauvais sens!

exemple: `$variable === 'toto'` => `'toto' === $variable`

2016-11-21 10:59 UTC, lapwil commented on Tests/Features/translation.feature
> +@GET @wip
un wip sauvage

2016-11-21 10:59 UTC, lapwil commented on app/Utils/Silex/EventSubscriber/ExceptionListener.php
> +                $code = 500;
ce n'est pas aligné ici

2016-11-21 13:36 UTC, rinaz-a commented on app/Utils/Silex/EventSubscriber/ExceptionListener.php
> +                $code = 500;
oui je n'avais pas commit le déplacement de la variable header #boulay mais c'est solved :)

2016-11-23 10:11 UTC, lapwil approved these changes
OK

2016-11-24 13:39 UTC, misseur approved these changes

2016-11-25 09:16 UTC, gdubost commented on .sync.yml
> +        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/translation-service-provider)]"
C'est quoi ce fichier ??

2016-11-25 09:19 UTC, gdubost commented on behat.yml
> +                - ETNA\FeatureContext\AuthContext
Ah bon ?

2016-11-25 09:21 UTC, gdubost commented on src/TranslationProvider.php
> +                    $tokens = json_decode($tokens["Translation"], true);
Wat ?

Tes headers font donc `$headers['Translation']['Translation']` ??

2016-11-25 09:47 UTC, rinaz-a commented on behat.yml
> +                - ETNA\FeatureContext\AuthContext
bah c'est partout j'ai supposé que fallait le mettre pour des éventuels futurs tests mais c'est con de le load pour rien je vais l'enlever

2016-11-25 11:03 UTC, rinaz-a commented on src/TranslationProvider.php
> +                    $tokens = json_decode($tokens["Translation"], true);
non c'est bien $headers['Translation'] mais quand tu get ça te garde la clée

2016-11-28 08:30 UTC, gdubost commented
Ils sont passes ou les badges du readme ?

2016-11-28 08:32 UTC, TinyTinyKame requested changes

2016-11-28 08:32 UTC, TinyTinyKame commented on Tests/Features/translation.feature
> +Scénario: On cherche à traduire un message après un app->abort
tous tes noms de scénarios sont les mêmes

2016-11-28 08:41 UTC, rinaz-a commented
Je m'occupe de remonter les badges et modifier les noms de scénario ;)

2016-11-30 14:30 UTC, misseur approved these changes
A part Schrutinizer qui meurt à petit feu (3222 minutes qu'il mouline dans le vent 😄 ), ça me semble ok :)

2016-11-30 16:26 UTC, gdubost commented on README.md
> +
Rajoute celui la :
```
[![Build Status](http://drone.etna-alternance.net/api/badge/github.com/etna-alternance/composer-translation-provider/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-translation-provider)
```

2016-12-01 09:04 UTC, gdubost commented on Tests/Bootstrap/FeatureContext.php
> +    public function jeDevraisAvoirUnResultatDApiEnJSON()
On a fait un composer pour éviter ce genre de choses, surtout que le doctrine context a priori t'es pas sense l'utiliser ^^

2016-12-01 09:06 UTC, gdubost commented on app/Utils/Silex/EventSubscriber/ExceptionListener.php
> +        if (is_a($exception, "Symfony\Component\HttpKernel\Exception\HttpException")) {
Si c'est nécessaire au bon fonctionnement de ton provider, ca doit en faire parti et être register par ton provider et pas seulement faire parti de l'app de test ^^

2016-12-01 09:10 UTC, gdubost commented on src/TranslationProvider.php
> +                            $content = str_replace($variable, $value, $content);
Tu peux le faire en un seul appel a str_replace :)

Je t'invite a lire le man :D

2016-12-05 09:39 UTC, lapwil approved these changes
Ca me semble correc'

2016-12-05 09:51 UTC, TinyTinyKame commented on phpmd.xml
> +    <description> phpmd ruleset for studentmanager-api</description>
studentmanager-api

2016-12-05 09:51 UTC, TinyTinyKame commented on src/TranslationProvider.php
> +                    'locale_fallbacks' => ['fr']
hmmmm, je suis pas trop fan de ça en vrai, ça devrait fallback sur du `en` quand il n'y a pas la traduction `fr`

2016-12-05 10:13 UTC, Hazainn commented on Tests/Bootstrap/FeatureContext.php
> +    public function jeDevraisAvoirUnResultatDApiEnJSON()
@rinaz-a: du coup tu as fais quelque chose pour ce commentaire ?

2016-12-05 10:13 UTC, Hazainn commented on app/Utils/Silex/EventSubscriber/ExceptionListener.php
> +                break;
c'est pas forcément très utile les retours à la ligne après les break.

2016-12-05 10:13 UTC, Teegie commented on src/ExceptionListenerWithHeaders.php
> +        }
ici aussi pour les espaces après les breaks.

2016-12-05 10:13 UTC, Teegie commented on src/ExceptionListenerWithHeaders.php
> +}
ce code ressemble énormément à celui-la : 
- `Utils/Silex/EventSubscriber/ExceptionListener.php`

il y a une raison ?

2016-12-05 10:42 UTC, rinaz-a commented on src/ExceptionListenerWithHeaders.php
> +}
yep, pour que quoi qu'il arrive on greffe les headers à la response, qu'il y ai ou non un exceptionListener dans l'app de base ;)

2016-12-05 13:56 UTC, rinaz-a commented on src/TranslationProvider.php
> +                    'locale_fallbacks' => ['fr']
en fait c'est juste pour setter une locale si la requête n'en contient pas, pour moi comme on est en france ça devrait être fr, dans tous les cas si il n'y a pas de traduction fr le message est renvoyé en anglais, je veux bien changer mais de toutes façons c'est quasi impossible que la requête ne contient pas de locale, je l'ai mis plus par principe ce check

2016-12-05 13:58 UTC, rinaz-a commented on Tests/Bootstrap/FeatureContext.php
> +    public function jeDevraisAvoirUnResultatDApiEnJSON()
Merci pour l'iddentification, j'étais pas remonté, non je touche pas car dans le `ApiContext` encore une fois on appelle `DoctrineContext` et que je n'en veux pas : 
```
    /**
     * @When /^je fais un (GET|POST|PUT|DELETE|OPTIONS) sur ((?:[a-zA-Z0-9,:!\/\.\?\&\=\+_%-]*)|"(?:[^"]+)") avec le JSON suivant :$/
     */
    public function jeFaisUneRequetteHTTPAvecDuJSON($method, $url, $body)
    {
        if (preg_match('/^".*"$/', $url)) {
            $url = substr($url, 1, -1);
        }

        if ($body !== null) {
            if (is_object($body)) {
                $body = $body->getRaw();
            }
            $this->request["headers"]["Content-Type"] = 'application/json';
            // add content-length ...
        }

        if (null === $body && isset($this->request["headers"]["Content-Type"])) {
            unset($this->request["headers"]["Content-Type"]);
        }

        $request = Request::create($this->base_url . $url, $method, [], [], [], [], $body);
        $request->headers->add($this->request["headers"]);
        $request->cookies->add($this->request["cookies"]);
        $request->files->add($this->request["files"]);

        $response = self::$silex_app->handle($request, HttpKernelInterface::MASTER_REQUEST, true);

        $result = [
            "http_code"    => $response->getStatusCode(),
            "http_message" => Response::$statusTexts[$response->getStatusCode()],
            "body"         => $response->getContent(),
            "headers"      => array_map(
                function ($item) {
                    return $item[0];
                },
                $response->headers->all()
            ),
        ];

        $this->getContext('ETNA\FeatureContext\DoctrineContext')->checkMaxQueries($method, $result);

        $this->response = $result;
    }
```

2016-12-08 09:07 UTC, TinyTinyKame approved these changes
Okay

2016-12-08 09:32 UTC, staciekith approved these changes
okay % drone

2016-12-08 09:49 UTC, misseur approved these changes

2016-12-08 17:04 UTC, gdubost commented on src/ExceptionListenerWithHeaders.php
> +        );
Ce listener fait trop de choses, je l'imaginais uniquement ajouter les headers à la réponse

2016-12-09 09:22 UTC, lapwil requested changes

2016-12-09 09:22 UTC, lapwil commented on Tests/Bootstrap/FeatureContext.php
> +        if ("" == $this->response['body']) {
tu pourrais la `trim()` histoire d'être sûr que c'est une chaîne "vide" et tu pourrais `===`

2016-12-09 13:31 UTC, rinaz-a commented on src/ExceptionListenerWithHeaders.php
> +        );
j'ai limité au max là @gdubost

2016-12-09 14:28 UTC, misseur approved these changes

2016-12-12 07:50 UTC, gdubost commented on src/ExceptionListenerWithHeaders.php
> +        );
Même avec :
```
$response = $event->getResponse();
$response->setHeaders(...);
$event->setResponse($response);
```

2016-12-14 09:49 UTC, lapwil approved these changes
Ca me semble bien maintenant 😄

2016-12-14 14:51 UTC, lennuyp approved these changes

2016-12-16 09:26 UTC, TinyTinyKame approved these changes
Ça m'a l'air bon

2016-12-16 10:18 UTC, merged